services:
  postgres-brt:
    container_name: flashcards-db
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - .pg/storage:/var/lib/postgresql/data
    # add code for db initialization 
      # - ./flashcards-api/src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flashcards